### ISSUE TITLE
Please add documentation on how to use the plugin

### ISSUE THREAD

**Issue by ayou392** [opeepl/chartjs-plugin-groupedlegend#3]
Hi,

Can you please add some documentation or an example on how to use the plugin.

Thanks in advance

**Comment by Voodu** [comment]
Hi @ayou392 

We'll add the proper readme file soon. For now, please use this Stackblitz example as a starting point https://stackblitz.com/edit/js-pg1s2c?file=index.js

The plugin should work with bar charts and line charts from ChartJS v3 and v4.

**Comment by ayou392** [comment]
Hi @Voodu,

That was very helpful.

Thank you

**Comment by Voodu** [comment]
Now there's a bit more readable README and some example code https://github.com/opeepl/chartjs-plugin-groupedlegend/pull/4
